/* eslint max-len: 0 */
/* eslint react/no-unescaped-entities: 0 */
/* eslint no-script-url: 0 */

import React from 'react';
import Helmet from 'react-helmet';
import Footer from '../components/Footer';
import Container from '../components/Container';
import Header from '../components/Header';
import config from '../../config/website';

const DataProtection = () => (
  <React.Fragment>
    <Helmet title={`Data Protection | ${config.siteTitle}`} />
    <Header title="Data Protection" />
    <div style={{ marginTop: '3rem' }}>
      <Container type="article">
        <h2>Data Protection</h2>
        <p>
          The operators of these pages take the protection of your personal data very seriously. We treat yours personal
          data confidential and in accordance with the statutory data protection regulations and this Data protection.
        </p>
        <p>
          The use of our website is usually possible without providing personal information. As far as ours data (such
          as name, address or e-mail addresses) are collected as far as possible, always on a voluntary voluntary basis.
          These data are provided without your express consent not disclosed to third parties.
        </p>
        <p>
          Please note that data transmission over the Internet (for example, when communicating by e-mail)
          Vulnerabilities may have. A complete protection of the data from access by third parties is not possible.
        </p>
        <h2>Cookies</h2>
        <p>
          The internet pages partly use so-called cookies. Cookies do not harm your computer and contain no viruses.
          Cookies serve to make our offering more user-friendly, effective and secure close. Cookies are small text
          files that are stored on your computer and your browser stores.
        </p>
        <p>
          Most of the cookies we use are so-called "session cookies". They will be after your end Visit automatically
          deleted. Other cookies remain stored on your device until you delete them. These cookies allow us to recognize
          your browser the next time you visit.
        </p>
        <p>
          You can set your browser so that you are informed about the setting of cookies and cookies only in individual
          cases, to exclude the acceptance of cookies for specific cases or in general as well as the Enable automatic
          deletion of cookies when closing the browser. When disabling cookies can the functionality of this website may
          be restricted.
        </p>
        <h2>Google Analytics</h2>
        <p>
          This website uses functions of the web analytics service Google Analytics. Provider is Google Inc., 1600
          Amphitheater Parkway Mountain View, CA 94043, USA.
        </p>
        <p>
          Google Analytics uses so-called "cookies". These are text files stored on your computer and that allow an
          analysis of the use of the website by you. The cookies generated by the cookie Information about your use of
          this website is usually sent to a Google server in the US transferred and stored there.
        </p>
        <p>
          For more information about how to handle user data on Google Analytics, please see the privacy policy of
          Google:{' '}
          <a href="https://support.google.com/analytics/answer/6004245">
            https://support.google.com/analytics/answer/6004245
          </a>
        </p>
        <h4>Browser Plugin</h4>
        <p>
          You can prevent the storage of cookies by a corresponding setting of your browser software; however, we point
          out that in this case you may not have all the functions of this Website can be fully exploited. You can also
          capture the information provided by the cookie generated and related to your use of the website data
          (including your IP address) to Google and the Prevent Google from processing this data by using the link
          available at the following link Download and install browser plugin:{' '}
          <a href="https://tools.google.com/dlpage/gaoptout">https://tools.google.com/dlpage/gaoptout</a>
        </p>
        <h4>Opposition to data collection</h4>
        <p>
          You can prevent the collection of your data by Google Analytics by clicking on the following link. An opt-out
          cookie will be set up to record your data on future visits to this site prevents:{' '}
          <a href="javascript:gaOptout();">Google Analytics deactivate</a>
        </p>
        <h4>IP-Anonymization</h4>
        <p>
          We use the function "activation of IP anonymization" on this website. This will be your IP address by Google,
          however, within Member States of the European Union or in other Contracting States of the Agreement on the
          European Economic Area previously shortened. Only in exceptional cases will the full IP address transferred to
          a Google server in the US and shortened there. On behalf of the operator of this website Google will use this
          information to evaluate your use of the website to provide reports on the Website activity and other related
          to website activity and internet usage Provide services to the website operator. The as part of Google
          Analytics from your Browser submitted IP address will not be merged with other data provided by Google.
        </p>
        <h2>SSL-Encoding</h2>
        <p>
          Diese Seite nutzt aus Gründen der Sicherheit und zum Schutz der Übertragung vertraulicher Inhalte, wie zum
          Beispiel der Anfragen, die Sie an uns als Seitenbetreiber senden, eine SSL-Verschlüsselung. Eine
          verschlüsselte Verbindung erkennen Sie daran, dass die Adresszeile des Browsers von "http://" auf "https://"
          wechselt und an dem Schloss-Symbol in Ihrer Browserzeile.
        </p>
        <p>
          This site is used for security reasons and to protect the transmission of sensitive content, such as Example
          of requests you send to us as a site operator, an SSL encryption. A encrypted connection, you can tell by the
          browser's address bar from "http: //" to "https: //" changes and to the lock icon in your browser line.
        </p>
      </Container>
    </div>
    <Footer />
  </React.Fragment>
);

export default DataProtection;
